### ISSUE TITLE
[Question] Possible to fence TS Path alias vs absolute importing?

### ISSUE THREAD

**Issue by philipgriffin** [smikula/good-fences#128]
I just started using good-fences and so far it is working out great, excellent work on it!

I am wondering if it is possible to enforce TS Path alias' over absolute imports.

For example, I have a fence configured so that A can import from B.

```jsonc
# a/fence.json
{
  "tags": ["A"],
  "exports": ["index"],
  "imports": [],
  "dependencies": [""]
}

```

```jsonc
# b/fence.json
{
  "tags": ["B"],
  "exports": [],
  "imports": ["A"],
  "dependencies": [""]
}

```

In a .ts file this **works correctly** and I receive an error if I try to import directly ie:
`import { data } from 'b/some/data'`

If I change this import to;

`import { data } from 'b/index'`

all is working as expected.

I am using TS Path Alias', **which does work fine**:
```jsonc
{
  "compilerOptions": {
    "paths": {
      "@b": ["b/index"],
    }
  }
}
```

`import { data } from '@b'

However, I would like to block the absolute import of b/index. So the TS Path alias must be used. Is this possible?

Hoping to have good-fences throw a complaint for `import { data } from 'b/index'` and only allow `import { data } from '@b'`.

**Comment by jpike88** [comment]
sounds like something a linter is more appropriate for handling.

see https://github.com/dword-design/eslint-plugin-import-alias
