### ISSUE TITLE
Consider porting to TSLint

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [smikula/good-fences#31]
This would likely end up in tslint-microsoft-contrib.

I've really enjoyed this tool, but it's been a little frustrating not having IDE-time errors.

**Comment by smikula** [comment]
I seriously considered doing this as a TSLint rule, but eventually decided that it veers pretty from the way TSLint works -- primarily the fact that the "rule" depends on config files that are distributed throughout the codebase, whereas (as far as I know) all other TSLint rules can run based on just the source file and the TSLint configuration.

However, IDE integration would be a great feature, and one that I'd love to work on if I can squeeze out time for it.  I've opened #32 to track integrating with VSCode.

**Comment by JoshuaKGoldberg** [comment]
> all other TSLint rules can run based on just the source file and the TSLint configuration

If it helps, there are now "typed" rules that take in the full TypeScript Program. Agreed that reading from config files is against the typical spirit of the project.
