### ISSUE TITLE
Getting an error 'No such file or directory' when running gf cli

### ISSUE THREAD

**Issue by zabirauf** [smikula/good-fences#33]
I'm running into an issue where I've added good fences in the project as dev dependency and as part of the build script I run `gf`. I'm getting into the following error

```
env: node\r: No such file or directory
```

**Comment by smikula** [comment]
Running `gf` will only work if it's in your path.  It will be if you install it globally (`npm install -g good-fences`) but not if it's in your project's node_modules.  If you're running it as part of a build process I suggest you use the API rather than calling the CLI, something like this:

```typescript
import * as goodFences from 'good-fences';

goodFences.run({
    // Options go here
});
```
